language: generic

sudo: required

services:
  - docker
script:
  - docker run --rm --volume ${TRAVIS_BUILD_DIR}:/nenuzhnix -e TRAVIS="$TRAVIS" tpimh/nenuzhnix-build:latest /bin/sh -l -c "/install.sh && /build.sh"
